name: Quality
on: push
jobs:
    cs-fixer:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Cs-Fixer
                run: |
                    wget -q https://cs.symfony.com/download/php-cs-fixer-v3.phar -O php-cs-fixer
                    chmod a+x php-cs-fixer
                    PHP_CS_FIXER_IGNORE_ENV=true ./php-cs-fixer fix src --dry-run

    phpstan5:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/cache@v3
                with:
                    path: '**/vendor'
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: php-actions/composer@v6
                with:
                    args: '--prefer-dist'
                    php_version: '8.2'
            -   name: PHPStan
                uses: php-actions/phpstan@v3
                with:
                    path: src/
                    level: 5
                    php_version: '8.2'

    phpstan6:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/cache@v3
                with:
                    path: '**/vendor'
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: php-actions/composer@v6
                with:
                    args: '--prefer-dist'
                    php_version: '8.2'
            -   name: PHPStan
                uses: php-actions/phpstan@v3
                with:
                    path: src/
                    level: 6
                    php_version: '8.2'

    phpstan7:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/cache@v3
                with:
                    path: '**/vendor'
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: php-actions/composer@v6
                with:
                    args: '--prefer-dist'
                    php_version: '8.2'
            -   name: PHPStan
                uses: php-actions/phpstan@v3
                with:
                    path: src/
                    level: 7
                    php_version: '8.2'

    phpstan8:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/cache@v3
                with:
                    path: '**/vendor'
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: php-actions/composer@v6
                with:
                    args: '--prefer-dist'
                    php_version: '8.2'
            -   name: PHPStan
                uses: php-actions/phpstan@v3
                with:
                    path: src/
                    level: 8
                    php_version: '8.2'
