on: [push, pull_request]
name: rector
jobs:
  rector:
    name: Rector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rector
        uses: zingimmick/rector-action@0.0.2
